### ISSUE TITLE
Features Request: automatic stop of the container when exiting app inside container and status refresh

### ISSUE THREAD

**Issue by NotMainstream** [Dvlv/BoxBuddyRS#76] opened 2024-03-29 14:22 UTC
Hello, you don t have a Feature Request category so I can only submit it as a Bug unfortunately.
It would be very useful if you can add a few features like:
-daily automatic update of the containers
-automatic stop of the container when exiting apps inside container
-automatic status refresh so we don t have to click refresh each container in BoxBuddy every time we want to see which containers still work in the background
-a clone button for the containers so we don t have to use the CLI every time
-add an export/import button for the containers so we can easily move them to other machines or VMs
-a size info section were we can have an overview of the containers size
-RAM usage info for every container

**Comment by Dvlv** [comment] 2024-03-29 15:27
Hello
BoxBuddy is just a UI for distrobox, so I don't want to start adding anything "autonomous".

> -daily automatic update of the containers
Out of scope for a UI

> -automatic stop of the container when exiting apps inside container
Out of scope for a UI

> -automatic status refresh so we don t have to click refresh each container in BoxBuddy every time we want to see which containers still work in the background
 The status does refersh when appropriate. The problem is, to refresh the status, I have to fetch the list of all boxes again, which is somewhat expensive.

> -a clone button for the containers so we don t have to use the CLI every time
Will add this to the roadmap.

> -add an export/import button for the containers so we can easily move them to other machines or VMs
I had this in the old C++ version, but the problem is once you re-import a container it has an image name like `localhost:my-box` so the UI is then unable to parse its distro, which breaks functionality. For that reason, I won't be adding this feature again.

> -a size info section were we can have an overview of the containers size
Is there a distrobox command for this? If so could you please link it.

> -RAM usage info for every container
As above, I can't see how to get this information.

**Comment by VortexAcherontic** [comment] 2024-03-29 20:52
I think in theory you can use: `podman stats` for ram and cpu usage of running podman containers. Don't know for Docker though so it might not work on systems using Docker.

**Comment by Dvlv** [comment] 2024-03-30 16:06
I've made #77 and #78 to track these. I'll close this issue and you can follow the new ones if you're interested.

**Closed by Dvlv** 2024-03-30 16:06 UTC
Labels: 🔎 Needs Investigation
