### ISSUE TITLE
Flatpak Translations Not Working

### ISSUE THREAD

**Issue by albanobattistella** [Dvlv/BoxBuddyRS#57] opened 2024-02-18 09:51 UTC
HI,

Italian language is not available.
Could you please check it?
Thanks.
A.

**Comment by Dvlv** [comment] 2024-02-18 13:28
Indeed the flatpak from flathub has no translations, but if I build a flatpak locally they work fine. Confusing.

Attempting a hotfix through flathub, but if it doesn't work I really don't know.

**Comment by Dvlv** [comment] 2024-02-19 06:58
Should be fixed now.

**Comment by albanobattistella** [comment] 2024-02-19 13:50
> Should be fixed now.

Hi, I tried just now, no italian language available.

**Comment by Dvlv** [comment] 2024-02-19 14:05
![image](https://github.com/Dvlv/BoxBuddyRS/assets/4907493/3f7d2664-1f3b-45ac-a6f9-e821b8387571)
Works for me with the latest from Flathub

**Comment by Dvlv** [comment] 2024-02-21 16:38
From playing around in some VMs, I'm even more confused.
It seems that the translations don't work for me on a fresh install, but if I build the local flatpak, they suddenly start working. Even if I purge the local flatpak and uninstall flatpak itself, the flathub packages will then forever be translated.

I have absolutely no idea what's going on, so all I can do now is hope someone who knows what they're doing sees this and is able to help out.

**Comment by VortexAcherontic** [comment] 2024-02-23 10:43
The German translation seems to work fine. Just tested it on a 2nd machine.

**Comment by VortexAcherontic** [comment] 2024-02-23 11:36
I just setup a new Italian virtual machine and installed flatpak, boxbuddy, podman and distrobox into that VM and everything seems to be in the correct system language.

![image](https://github.com/Dvlv/BoxBuddyRS/assets/11244092/a98558e6-a181-44dc-8971-4be1c40a2152)

I think it is more likely there is something wrong with the locale on affected systems.

**Comment by Dvlv** [comment] 2024-02-24 10:08
I wonder if it's because I install my VMs in en_GB then switch the language in GNOME settings after-the-fact. :thinking: 

Either way, still very unexpected behaviour.

**Comment by Dvlv** [comment] 2024-03-10 10:25
No movement on this, so I'm gonna close it.
If we get more reports of this issue, we can reopen this (not that I have any idea what to do about it).

**Closed by Dvlv** 2024-03-10 10:25 UTC
Labels: 🐛 Bug, ❗Help Wanted, 🪑 Flatpak-only
